const IMAGES = {
    backgroundLogo: require('../Images/3.png').default,
    cssLogo: require('../Images/css.png').default,
    javascriptLogo: require('../Images/javascript.png').default,
    jqueryLogo: require('../Images/jquery.png').default,
    nodejsLogo: require('../Images/nodejs.png').default,
    adobeXDLogo: require('../Images/adobeXD.png').default,
    adobeprLogo: require('../Images/adobepr.png').default,
    aftereffectLogo: require('../Images/aftereffect.png').default,
    bootstrapLogo: require('../Images/bootstrap.png').default,
    bulmaLogo: require('../Images/bulma-logo.png').default,
    handlebarsLogo: require('../Images/handlebars-js.png').default,
    photoshopLogo: require('../Images/photoshop.png').default,
    mysqlLogo: require('../Images/mysql.png').default,
    ExpressJSLogo: require('../Images/ExpressJS.png').default,
    greensockLogo: require('../Images/greensock-logo.svg').default,
    moviefinderLogo: require('../Images/moviefinder.png').default,
    DeliciosooLogo: require('../Images/Deliciosoo.png').default,
    dayplannerLogo: require('../Images/dayplanner.png').default,
    ballfinderLogo: require('../Images/ballfinder.gif').default,
    techLogo: require('../Images/tech-news.png').default,
    Animation: require('../Images/Animation.gif').default,
    weatherproject: require('../Images/weatherproject.png').default,
}

export default IMAGES;